version: '3'
services:
  app:
    container_name: app
    image: msal4/shashety-backend:latest
    restart: always
    build: .
    ports:
      - '80:80'
    links:
      - mongo
    command: 'npx pm2 start ecosystem.config.js --no-daemon'
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
